### ISSUE TITLE
Plugin install script for OpenSlides

### ISSUE THREAD

**Issue by jsaalfeld** [OpenSlides/openslides-docker#2]
Enhance the script in a way, that you can provide Names for OpenSlides Plugins (like https://github.com/OpenSlides/openslides-voting) as a build arg, so they will be automatically build in and activated, when started:

```
version: '3'
services:
  core:
    build:
      context: ./core
      args:
        # Change according to your details
        REPOSITORY_URL: https://github.com/OpenSlides/OpenSlides.git
        BRANCH: master
        COMMIT_SHA: 03b17837ed2c88692f1b99ec5b9b477f86fdddb6
        PLUGINS: openslides-voting,openslides-conversations
    image: openslides
    command: bash -c "python manage.py migrate && python manage.py collectstatic --noinput"
    depends_on:
      - postgres
    volumes:
      - "staticfiles:/app/personal_data"
    networks:
      - back
```
